### ISSUE TITLE
solver.py unable to open encoding.lp

### ISSUE THREAD

**Issue by ptal0003** [tortinator/asprilo#14]
Hi
I am trying to use the incremental solver in asprilo. When I click on solve/fast solve, it gives me an error saying "encoding.lp could not be opened."
I am new working with asprilo, could you tell me the path where the encoding.lp is meant to be? I suspect this to be an issue of incorrect path. Also, is there a separate encoding.lp file for each plan or can a common one be used?
This error is due to the line shown in the snippet below:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/62492172/145358119-8d1e60ee-27b5-48b1-a4b3-7e1506c301f7.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/62492172/145357998-bb27e77f-2ac6-46a4-ac0c-f0178a465bfd.png">

**Comment by pobermei** [comment]
The `solver.py` example was developed & used by a former student and  is essentially abandoned. Specifically, I never used `solver.py` myself but  visualize instances and  plans post-mortem as explained [here](https://github.com/potassco/asprilo/blob/master/docs/visualizer.md#loading-instancesplans
)
This is also the typical workflow of our current students.

**Comment by ptal0003** [comment]
Is there a solver that is being currently used with asprilo which I could have a look at?

**Comment by pobermei** [comment]
> Is there a solver that is being currently used with asprilo which I could have a look at?

If you mean a python script like `solver.py` that [communicates via network with the visualizer](https://github.com/potassco/asprilo/blob/master/docs/visualizer.md#solver), not that I'm aware of.
