### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ghost** [tortinator/asprilo#7]
Is there a description on how to install everything in order to work with it?

**Comment by pobermei** [comment]
Those are all regular ASP encodings meant to be run with [clingo](https://potassco.org/clingo/). As a starting point, you can try to run this [example invocation](https://github.com/potassco/asprilo-encodings#invocation-examples).

**Comment by ptal0003** [comment]
I am able to get ASPRILO running and I have loaded an instance in the visualiser as well. However, I do not understand how to run the plan to see a simulation? I am trying to generate a plan through the solver, but every time I try to connect to the solver, I see this error:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/62492172/145209969-9966b5de-4bb2-4efe-92c0-0ececd79e7f0.png">

**Comment by pobermei** [comment]
> I am able to get ASPRILO running and I have loaded an instance in the visualiser as well. However, I do not understand how to run the plan to see a simulation? I am trying to generate a plan through the solver, but every time I try to connect to the solver, I see this error: <img alt="image" width="571" src="https://user-images.githubusercontent.com/62492172/145209969-9966b5de-4bb2-4efe-92c0-0ececd79e7f0.png">

It seems that the `solver.py`  example is not compatible with python>=3.8 where `time` has no more `clock` attribute. I'll add this to the backlog

**Comment by ptal0003** [comment]
Could you tell me how to add a solver to asprilo if this method does not work? Is there a way that I'd be able to use the default solver without modifying asprilo?

**Comment by ptal0003** [comment]
How do I use any solver with asprilo?

**Comment by pobermei** [comment]
> Could you tell me how to add a solver to asprilo if this method does not work? Is there a way that I'd be able to use the default solver without modifying asprilo?

Only the  `solver.py` example needs to be upgraded for compatibility w/ Python>=3.8 but not the visualizer itself. Hence, if you write your own updated solver script similar to `solver.py`, it should work with the current visualizer. 

In case you upgrade `solver.py`, feel free to open a PR for it.
